import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAuditLog1765489607985 implements MigrationInterface {
    name = 'CreateAuditLog1765489607985'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "expenses_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "expenses_matter_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "expenses_invoice_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "invoice_line_items_invoice_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "invoice_line_items_time_entry_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "invoice_line_items_expense_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP CONSTRAINT "trust_accounts_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_trust_account_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_matter_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_related_invoice_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "trust_transactions_created_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_invoice_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "payments_trust_transaction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_matter_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_invoice_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_matter_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "tasks_assigned_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_matter_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "documents_uploaded_by_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "matters_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "matters_client_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "matters_responsible_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "clients_firm_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_firm_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expenses_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expenses_matter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_line_items_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trust_accounts_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trust_transactions_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trust_transactions_client"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trust_transactions_matter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trust_transactions_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_invoices_client"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_entries_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_entries_matter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_entries_billed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_matter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_due"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_matter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matters_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matters_client"`);
        await queryRunner.query(`DROP INDEX "public"."idx_matters_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_firm"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_created"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_hours_check"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "invoices_firm_id_invoice_number_key"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "matters_firm_id_matter_number_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_firm_id_email_key"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "firm_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "operation"`);
        await queryRunner.query(`DROP TYPE "public"."audit_operation"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "old_values"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "new_values"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resource" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "resourceId" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ipAddress" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userAgent" character varying`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "timestamp" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "billable" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "billed" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."tax_treatment" RENAME TO "tax_treatment_old"`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_tax_treatment_enum" AS ENUM('taxable', 'exempt', 'zero_rated')`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" TYPE "public"."expenses_tax_treatment_enum" USING "tax_treatment"::"text"::"public"."expenses_tax_treatment_enum"`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" SET DEFAULT 'taxable'`);
        await queryRunner.query(`DROP TYPE "public"."tax_treatment_old"`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."line_item_type" RENAME TO "line_item_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_line_items_line_type_enum" AS ENUM('time', 'expense', 'flat_fee', 'custom')`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "line_type" TYPE "public"."invoice_line_items_line_type_enum" USING "line_type"::"text"::"public"."invoice_line_items_line_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."line_item_type_old"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ALTER COLUMN "currency" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ALTER COLUMN "current_balance" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."trust_transaction_type" RENAME TO "trust_transaction_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."trust_transactions_transaction_type_enum" AS ENUM('deposit', 'transfer_to_fees', 'refund', 'interest', 'bank_charge')`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ALTER COLUMN "transaction_type" TYPE "public"."trust_transactions_transaction_type_enum" USING "transaction_type"::"text"::"public"."trust_transactions_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trust_transaction_type_old"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method" RENAME TO "payment_method_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('bank_transfer', 'credit_card', 'cheque', 'cash', 'trust_transfer')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_method" TYPE "public"."payments_payment_method_enum" USING "payment_method"::"text"::"public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_source" RENAME TO "payment_source_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_source_enum" AS ENUM('external', 'trust')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_source" TYPE "public"."payments_payment_source_enum" USING "payment_source"::"text"::"public"."payments_payment_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_source_old"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status" RENAME TO "invoice_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'viewed', 'partial', 'paid', 'overdue', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "subtotal" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_gst" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_pst" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_hst" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "amount_paid" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "balance_due" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billable" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."task_priority" RENAME TO "task_priority_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" TYPE "public"."tasks_priority_enum" USING "priority"::"text"::"public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET DEFAULT 'normal'`);
        await queryRunner.query(`DROP TYPE "public"."task_priority_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."task_status" RENAME TO "task_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."tasks_status_enum" USING "status"::"text"::"public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "shared_with_client" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."matter_status" RENAME TO "matter_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."matters_status_enum" AS ENUM('active', 'pending', 'closed', 'archived')`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" TYPE "public"."matters_status_enum" USING "status"::"text"::"public"."matters_status_enum"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."matter_status_old"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."billing_type" RENAME TO "billing_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."matters_billing_type_enum" AS ENUM('hourly', 'flat_fee', 'contingency', 'mixed')`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" TYPE "public"."matters_billing_type_enum" USING "billing_type"::"text"::"public"."matters_billing_type_enum"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" SET DEFAULT 'hourly'`);
        await queryRunner.query(`DROP TYPE "public"."billing_type_old"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "open_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "open_date" SET DEFAULT ('now'::text)::date`);
        await queryRunner.query(`ALTER TABLE "matters" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "matters" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matters" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "matters" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."client_type" RENAME TO "client_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."clients_client_type_enum" AS ENUM('individual', 'organization')`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" TYPE "public"."clients_client_type_enum" USING "client_type"::"text"::"public"."clients_client_type_enum"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."client_type_old"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "portal_enabled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "firms" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "firms" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "firms" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "firms" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "firms" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'lawyer', 'staff')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'staff'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "hourly_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_5cdadec4e2bd942d8fc9deab18c" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_1781ca6f69623bdd11594f03ec4" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_7b0e6a9fad3c2b49bb2d18a7bc7" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_e554609a06b180dac66a9a977c5" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_28ce773d4938d8bd361b88ea294" FOREIGN KEY ("time_entry_id") REFERENCES "time_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_7d166ed124a7f53d71e7d22a88b" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD CONSTRAINT "FK_2b5585ed11f779f49a04310d5fe" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_ad439a0e82f0d00fa1545540764" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_45a981fc996280e304ed6dcf3b7" FOREIGN KEY ("trust_account_id") REFERENCES "trust_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_8336464d0dd8902ec6e7970dc1a" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_5af5c2c7633dc31afc5c377eae3" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_21388dafd3ffec2e494bea3cbb5" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "FK_df1b09bc65948d9f92501b21898" FOREIGN KEY ("related_invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_4a225ecc06f82c8c5cea32cce1c" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_277db06fe9835d2ff8142133a82" FOREIGN KEY ("trust_transaction_id") REFERENCES "trust_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5a04eca43d4936b397d437dc1bf" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_cbd9fc7a93625c0006e393f609f" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_db2ea6f8ba6963d6948e2b17e8c" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_8776158e9ef020ce7b066dd20eb" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_07ec24432add067e9023e60d43c" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_098d5dc60db0e81221cc768141d" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_327d5ce9cd59770b274f8c3579f" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_5d0f793be458aab8fea1f7dc3e2" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_8324b7ffebc32c4fa47f7c16762" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_f6a0859c9b1c7c3fcb003c17163" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_6f8986d1406171fccbd6bb2d864" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "FK_bd5098d002707ef6a34bd8dc546" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "FK_01485a46141fcfa55fd498f8d06" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "FK_2c14c356105ba1a106d8722ceb9" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_ba8cbb5524f41304b63622d432a" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9ef0befe8cb0dbf7a2c7ae8b2f2" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9ef0befe8cb0dbf7a2c7ae8b2f2"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_ba8cbb5524f41304b63622d432a"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "FK_2c14c356105ba1a106d8722ceb9"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "FK_01485a46141fcfa55fd498f8d06"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP CONSTRAINT "FK_bd5098d002707ef6a34bd8dc546"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_6f8986d1406171fccbd6bb2d864"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_f6a0859c9b1c7c3fcb003c17163"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_8324b7ffebc32c4fa47f7c16762"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_5d0f793be458aab8fea1f7dc3e2"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_327d5ce9cd59770b274f8c3579f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_098d5dc60db0e81221cc768141d"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_07ec24432add067e9023e60d43c"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_8776158e9ef020ce7b066dd20eb"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_db2ea6f8ba6963d6948e2b17e8c"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_cbd9fc7a93625c0006e393f609f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5a04eca43d4936b397d437dc1bf"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_277db06fe9835d2ff8142133a82"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_4a225ecc06f82c8c5cea32cce1c"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_df1b09bc65948d9f92501b21898"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_21388dafd3ffec2e494bea3cbb5"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_5af5c2c7633dc31afc5c377eae3"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_8336464d0dd8902ec6e7970dc1a"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_45a981fc996280e304ed6dcf3b7"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP CONSTRAINT "FK_ad439a0e82f0d00fa1545540764"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP CONSTRAINT "FK_2b5585ed11f779f49a04310d5fe"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_7d166ed124a7f53d71e7d22a88b"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_28ce773d4938d8bd361b88ea294"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_e554609a06b180dac66a9a977c5"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_7b0e6a9fad3c2b49bb2d18a7bc7"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_1781ca6f69623bdd11594f03ec4"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_5cdadec4e2bd942d8fc9deab18c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "hourly_rate" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('admin', 'lawyer', 'staff')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'staff'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "firms" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "firms" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "firms" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "firms" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "firms" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "clients" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "portal_enabled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."client_type_old" AS ENUM('individual', 'organization')`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" TYPE "public"."client_type_old" USING "client_type"::"text"::"public"."client_type_old"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "client_type" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."clients_client_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."client_type_old" RENAME TO "client_type"`);
        await queryRunner.query(`ALTER TABLE "matters" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "matters" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matters" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "matters" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "open_date" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "open_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."billing_type_old" AS ENUM('hourly', 'flat_fee', 'contingency', 'mixed')`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" TYPE "public"."billing_type_old" USING "billing_type"::"text"::"public"."billing_type_old"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "billing_type" SET DEFAULT 'hourly'`);
        await queryRunner.query(`DROP TYPE "public"."matters_billing_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."billing_type_old" RENAME TO "billing_type"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."matter_status_old" AS ENUM('active', 'pending', 'closed', 'archived')`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" TYPE "public"."matter_status_old" USING "status"::"text"::"public"."matter_status_old"`);
        await queryRunner.query(`ALTER TABLE "matters" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."matters_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."matter_status_old" RENAME TO "matter_status"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "documents" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "shared_with_client" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "documents" ALTER COLUMN "version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_old" AS ENUM('pending', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_old" USING "status"::"text"::"public"."task_status_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_old" RENAME TO "task_status"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."task_priority_old" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" TYPE "public"."task_priority_old" USING "priority"::"text"::"public"."task_priority_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET DEFAULT 'normal'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_priority_old" RENAME TO "task_priority"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billable" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "balance_due" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "amount_paid" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_hst" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_pst" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "tax_gst" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "subtotal" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status_old" AS ENUM('draft', 'sent', 'viewed', 'partial', 'paid', 'overdue', 'written_off')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoice_status_old" USING "status"::"text"::"public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status_old" RENAME TO "invoice_status"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."payment_source_old" AS ENUM('external', 'trust')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_source" TYPE "public"."payment_source_old" USING "payment_source"::"text"::"public"."payment_source_old"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_source_old" RENAME TO "payment_source"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_old" AS ENUM('bank_transfer', 'credit_card', 'cheque', 'cash', 'trust_transfer')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "payment_method" TYPE "public"."payment_method_old" USING "payment_method"::"text"::"public"."payment_method_old"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_method_old" RENAME TO "payment_method"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."trust_transaction_type_old" AS ENUM('deposit', 'transfer_to_fees', 'refund', 'interest', 'bank_charge')`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ALTER COLUMN "transaction_type" TYPE "public"."trust_transaction_type_old" USING "transaction_type"::"text"::"public"."trust_transaction_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."trust_transactions_transaction_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."trust_transaction_type_old" RENAME TO "trust_transaction_type"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ALTER COLUMN "current_balance" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ALTER COLUMN "currency" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "quantity" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."line_item_type_old" AS ENUM('time', 'expense', 'flat_fee', 'custom')`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ALTER COLUMN "line_type" TYPE "public"."line_item_type_old" USING "line_type"::"text"::"public"."line_item_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_line_items_line_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."line_item_type_old" RENAME TO "line_item_type"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."tax_treatment_old" AS ENUM('taxable', 'exempt', 'zero_rated')`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" TYPE "public"."tax_treatment_old" USING "tax_treatment"::"text"::"public"."tax_treatment_old"`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "tax_treatment" SET DEFAULT 'taxable'`);
        await queryRunner.query(`DROP TYPE "public"."expenses_tax_treatment_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tax_treatment_old" RENAME TO "tax_treatment"`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "billed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "billable" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userAgent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resourceId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "resource"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" inet`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "new_values" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "old_values" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."audit_operation" AS ENUM('create', 'read', 'update', 'delete')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "operation" "public"."audit_operation" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "firm_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_firm_id_email_key" UNIQUE ("firm_id", "email")`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "matters_firm_id_matter_number_key" UNIQUE ("firm_id", "matter_number")`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_firm_id_invoice_number_key" UNIQUE ("firm_id", "invoice_number")`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_hours_check" CHECK ((hours >= (0)::numeric))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_firm" ON "audit_logs" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_users_firm" ON "users" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_firm" ON "clients" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matters_status" ON "matters" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_matters_client" ON "matters" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_matters_firm" ON "matters" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_matter" ON "documents" ("matter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_firm" ON "documents" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_due" ON "tasks" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_matter" ON "tasks" ("matter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_firm" ON "tasks" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_time_entries_billed" ON "time_entries" ("billed") `);
        await queryRunner.query(`CREATE INDEX "idx_time_entries_matter" ON "time_entries" ("matter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_time_entries_firm" ON "time_entries" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_client" ON "invoices" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_status" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_invoices_firm" ON "invoices" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_invoice" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_firm" ON "payments" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trust_transactions_date" ON "trust_transactions" ("transaction_date") `);
        await queryRunner.query(`CREATE INDEX "idx_trust_transactions_matter" ON "trust_transactions" ("matter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trust_transactions_client" ON "trust_transactions" ("client_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trust_transactions_firm" ON "trust_transactions" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trust_accounts_firm" ON "trust_accounts" ("firm_id") `);
        await queryRunner.query(`CREATE INDEX "idx_line_items_invoice" ON "invoice_line_items" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expenses_matter" ON "expenses" ("matter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_expenses_firm" ON "expenses" ("firm_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "clients_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "matters_responsible_user_id_fkey" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "matters_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matters" ADD CONSTRAINT "matters_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_user_id_fkey" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_matter_id_fkey" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "documents_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assigned_user_id_fkey" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_matter_id_fkey" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "tasks_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_matter_id_fkey" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "invoices_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_trust_transaction_id_fkey" FOREIGN KEY ("trust_transaction_id") REFERENCES "trust_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "payments_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_related_invoice_id_fkey" FOREIGN KEY ("related_invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_matter_id_fkey" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_trust_account_id_fkey" FOREIGN KEY ("trust_account_id") REFERENCES "trust_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_transactions" ADD CONSTRAINT "trust_transactions_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_accounts" ADD CONSTRAINT "trust_accounts_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_expense_id_fkey" FOREIGN KEY ("expense_id") REFERENCES "expenses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_time_entry_id_fkey" FOREIGN KEY ("time_entry_id") REFERENCES "time_entries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "expenses_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "expenses_matter_id_fkey" FOREIGN KEY ("matter_id") REFERENCES "matters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "expenses_firm_id_fkey" FOREIGN KEY ("firm_id") REFERENCES "firms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
